version: "3.9"

services:
  backend:
    image: yourdockerhubuser/web-service-gin:latest
    ports:
      - "8085:8085"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/albumdb?sslmode=disable
    depends_on:
      - db

  frontend:
    image: yourdockerhubuser/albums-frontend:latest
    ports:
      - "3000:3000"

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: albumdb
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
